export global current_text {
    callback populate([string]);
}

component side_bar inherits Rectangle {
    width: 20%;
    height: 100%;
    background: #2A3424;
}

component main_text_area inherits Rectangle {
    width: 80%;
    height: 100%;
    background: #D9D9D9;
}

import { Button, VerticalBox } from "std-widgets.slint";
export component App inherits Window {

    min_width: 500px;
    min_height: 500px;

    in property <string> current_string;
    in property <[string]> current_text;

    GridLayout {
        width: 100%;
        height: 100%;
        Row {
            side_bar {}
            main_text_area {
                VerticalBox {
                    alignment: center;
                    padding: 10px;
                    spacing: 5px;
                    Text {
                        text: current_string;
                        color: black;
                        wrap: word-wrap;
                    }
//for t in current_text : Text {
//    text: t;
//    color: t == current_string ? red : black;
//    wrap: word-wrap;
//}
                }
            }
        }
    }
}
